# **Módulo 3: Modelos de Regressão Fundamentais - Exercício Prático**

Neste exercício, você irá se concentrar em aplicar os principais modelos de regressão linear e técnicas de regularização com Ridge e Lasso, utilizando o dataset de preços de casas pré-processado (`housing_tratado.csv`) que já utilizamos  no notebook do Módulo.

1. **Execute a primeira célula** para carregar o dataset.
2. Siga as instruções ao longo do notebook — os **comentários nas células indicam exatamente o que deve ser feito**, e os locais onde você deve preencher o código estarão claramente marcados com `'aqui'`, para facilitar o processo.
3. No final, utilize os resultados obtidos para responder às perguntas no espaço indicado no material do curso.


Execute a célula abaixo para começar.

## **Carregamento e Preparação dos Dados**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

url = "https://raw.githubusercontent.com/TreinamentoICCInatel/Curso_Regressao_na_Pratica/refs/heads/main/Arquivos/housing_tratado.csv"
housing = pd.read_csv(url)

# Use o comando head para verificar se o dataset foi carregado corretamente


Separe as variáveis independentes (X) da variável alvo (y). Em seguida, divida o conjunto de dados, reservando 30% das amostras para o conjunto de teste. Por fim, exiba o tamanho dos conjuntos de treino e teste.

In [ ]:
# Selecione a váriavel alvo do dataset
Y = housing['váriavel alvo']
X = housing.drop('variável alvo', axis=1)

# Importe o train_test_split
from sklearn.model_selection import

# Defina o tamanho solicitado para o conjunto de teste
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size= 'aqui', random_state=42)

print(f"Tamanho do Treino: {X_train.shape[0]} amostras")
print(f"Tamanho do Teste: {X_test.shape[0]} amostras")


#### **1. Qual é a latitude correta referente à observação inicial do dataset, juntamente com os tamanhos dos conjuntos de treino e teste após a divisão dos dados?**
a) A latitude registrada na primeira linha é 1.043185, e os conjuntos de treino e teste possuem, respectivamente, 14.448 e 6.192 amostras.

b) A latitude exibida na linha um é de 1.043185, enquanto os tamanhos resultantes da divisão são 14.448 para treino e 6.192 para teste.

c) A latitude da primeira linha é 1.052548, e os tamanhos dos conjuntos gerados são 16512 (treino) e 4128 (teste).

d) A latitude mostrada na linha zero do dataframe é -1.327835, e o conjunto de treino contém 14.448 amostras, enquanto o teste possui 6.192.

## **Entendendo o Modelo**

Instancie e treine o modelo de regressão linear com os dados separados na etapa anterior

In [ ]:
from sklearn import linear_model

# instancie o modelo de regressão linear com LinearRegression()
linear_model = linear_model.'aqui'

# treine o modelo (use X_train e y_train)
linear_model.fit('aqui')

# use X_test para gerar as previsões
y_pred_linear = linear_model.predict('aqui')


print(f"Intercepto (Beta 0): {linear_model.intercept_:.4f}")

coef_df = pd.DataFrame({
    'Feature': X_train.columns,
    'Coeficiente': linear_model.coef_
}).sort_values(by='Coeficiente', ascending=False)

display(coef_df)


#### **2. Com base na tabela de coeficientes gerada após a aplicação do modelo de Regressão Linear, qual das interpretações abaixo está correta?**

a) A variável `ocean_proximity_ISLAND` possui coeficiente negativo, indicando que morar em ilhas reduz o preço das casas, enquanto `ocean_proximity_INLAND` apresenta coeficiente positivo, sugerindo que áreas no interior tendem a ser mais valorizadas.

b) A variável `median_income` aparece com um dos maiores coeficientes positivos do modelo, indicando forte relação com preços mais altos, enquanto `population` apresenta coeficiente negativo, sugerindo que áreas mais populosas tendem a ter preços mais baixos.

c) A variável `latitude` apresenta coeficiente positivo, indicando que valores maiores de latitude aumentam o preço das casas, e `total_rooms` possui coeficiente positivo, indicando que um número maior de cômodos eleva o preço.

d) A variável `housing_median_age` possui coeficiente negativo, mostrando que casas mais antigas tendem a valer menos, enquanto `ocean_proximity_NEAR BAY` aparece com coeficiente positivo, indicando que proximidade de baía aumenta os preços.


## **PolynomialFeatures e Overfitting**

O código abaixo aplicaremos o `PolynomialFeatures` com **grau 3** na variável `median_income`.
Isso significa que, para cada valor original, o transformador irá gerar:

*  $x$
* $x^2$
* $x^3$

Ou seja, cada linha do novo conjunto X_poly terá três colunas, representando os termos polinomiais correspondentes ao mesmo valor de entrada.

Depois da transformação, o código irá imprimir as três primeiras linhas dessa matriz expandida.
Observe que os valores numéricos exibidos serão os próprios valores de median_income elevados a 1, 2 e 3.

In [ ]:
# importe o PolynomialFeatures
from sklearn.preprocessing import

# Selecione apenas a variável 'median_income'
X_ex = housing[['aqui']].values
y_ex = housing['median_house_value'].values

# Crie termos polinomiais até grau 3 (x, x², x³)
poly = PolynomialFeatures(degree= 'aqui', include_bias=False)

# Transformando os dados
X_poly = poly.fit_transform(X_ex)

# Treinando o modelo usando os dados polinomiais
modelo = LinearRegression()
modelo.fit(X_poly, y_ex)

# Mostrando as 3 primeiras linhas transformadas
print("Primeiras 3 linhas de X_poly:")
print(X_poly[:3])


#### **3. Qual das alternativas representa corretamente a saída do bloco?**

a)

[[2.30011211 5.29081210 11.80555120]

  [2.10199920 4.99021194 11.10012220]

 [1.70088212 3.00011881  5.20011910]] <br><br>



 b)

 [[2.34476576 12.89134971  5.49792646]

 [2.33223796 12.68582106  5.43933392]

 [1.7826994   5.66544930  3.17801716]] <br><br>

 c)

 [[ 2.34476576  5.49792646 12.89134971]

 [ 2.33223796  5.43933392 12.68582106]

 [ 1.7826994   3.17801716  5.6654493 ]]  <br><br>

 d)

 [[1.78269940  3.17801716  5.66544930]

 [2.34476576  5.49792646 12.89134971]

 [2.33223796  5.43933392 12.68582106]]





 Ao utilizar `PolynomialFeatures`, aumentar o parâmetro `degree` faz com que o modelo gere termos de ordem cada vez maior ($x^4$, $x^5$, $x^6$ e assim por diante).

#### **4. Se continuarmos aumentando o degree para valores muito altos, qual é o efeito mais provável no modelo treinado?**
a) O modelo tende a se tornar mais simples, reduzindo sua variância e evitando overfitting.

b) O modelo passa a ignorar completamente os termos mais altos, porque a regressão linear só usa o termo original x.

c) O modelo pode ficar extremamente complexo, ajustando até pequenos ruídos dos dados e aumentando o risco de overfitting.

d) Aumentar muito o degree não altera em nada o comportamento do modelo, pois todos os termos polinomiais acima do grau 3 são descartados automaticamente pela classe `LinearRegression`.

## **Regularização com Ridge e Lasso**

Agora vamos comparar dois tipos de regularização: Ridge (L2) e Lasso (L1).
O objetivo é observar como cada modelo afeta os coeficientes da regressão.
No código abaixo, você deve completar os trechos marcados como 'aqui' para:

* importar corretamente as classes Ridge e Lasso;

* definir os valores de alpha para cada modelo (Ridge = 1.0, Lasso = 0.01);

* preencher os parâmetros necessários para treinar o modelo Lasso.


Depois de completar o código, o programa exibirá os 5 primeiros coeficientes aprendidos por cada modelo, permitindo comparar como cada tipo de regularização atua sobre os pesos.

In [ ]:
# importe o Ridge
from sklearn.linear_model import
# importe o Lasso
from sklearn.linear_model import

# instancie o ridge com alpha = 1.0 e o Lasso com 0.01
ridge_model = Ridge(alpha= 'aqui')
lasso_model = Lasso(alpha= 'aqui')

# treinando o modelo ridge
ridge_model.fit(X_train, y_train)

# preencha as informações faltantes para treinar o modelo lasso
lasso_model.fit('aqui')

# imprimindo as primeiras 5 coeficientes de cada modelo
print("Coeficientes Ridge:", ridge_model.coef_[:5])
print("Coeficientes Lasso:", lasso_model.coef_[:5])


Após treinar os modelos Ridge e Lasso usando:

```
ridge_model = Ridge(alpha=1.0)
lasso_model = Lasso(alpha=0.01)
```
e observar que o Lasso não zera todos os coeficientes, mas ainda assim reduz alguns deles de forma mais agressiva do que o Ridge, responda:

#### **5. Qual comportamento é esperado do método Lasso em comparação ao Ridge?**
a) Com alpha=0.01, o Lasso passa a se comportar exatamente como o Ridge, mantendo todos os coeficientes próximos e evitando qualquer forma de redução agressiva.

b) Mesmo com um alpha baixo, o Lasso ainda pode zerar alguns coeficientes, produzindo um modelo mais esparso do que o Ridge, que tende apenas a reduzir valores sem zerá-los.

c) O Ridge tende a zerar coeficientes antes do Lasso quando o alpha é pequeno, pois sua penalização L2 força pesos a ficarem exatamente iguais a zero.

d) Com alpha=0.01, o Lasso deixa todos os coeficientes maiores do que os do Ridge, pois a penalização L1 fica muito fraca para afetar qualquer variável.





---

Com isso, concluímos nossa exploração dos principais modelos de regressão e técnicas de regularização.

Agora você já viu na prática como preparar os dados, treinar diferentes modelos, analisar seus coeficientes e entender o impacto da regularização.
Sinta-se à vontade para ajustar os valores de alpha, testar outras variáveis ou comparar novos modelos — essa é a melhor forma de aprofundar seu entendimento.

Ótimo trabalho até aqui!